services:
  # Backend API
  backend:
    build:
      context: ./backend
      target: development  # Changed to development for hot-reloading
    container_name: github-analyzer-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - NODE_OPTIONS=--max-old-space-size=1024
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - github-analyzer-network

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      target: development  # Changed to development for hot-reloading
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:5000  # Direct to backend
    container_name: github-analyzer-frontend
    ports:
      - "3000:3000"  # Changed to 3000 for Vite dev server
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - github-analyzer-network

networks:
  github-analyzer-network:
    driver: bridge
    name: github-analyzer-network

# Optional: Add volumes for persistent data
volumes:
  backend_data:
    name: github-analyzer-backend-data