version: '3.8'

services:
  backend:
    build:
      context: ./backend
      target: production
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - github-analyzer-network

  frontend:
    build:
      context: ./frontend
      target: production
    environment:
      - NODE_ENV=production
      - VITE_API_URL=/api
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - github-analyzer-network

networks:
  github-analyzer-network:
    driver: bridge
    name: github-analyzer-network

volumes:
  backend_data:
    name: github-analyzer-backend-data
