version: '3.8'

services:
  backend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - DEBUG=app:*,github:*
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
      - "9229:9229"  # Node.js debug port
    command: >
      sh -c "npm install && 
             npm run dev"

  frontend:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"  # Vite dev server port
    command: >
      sh -c "npm install && 
             npm run dev"
